# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir sync
    cd sync
    git clone https://github.com/MephistoSunyang/bravo-seed.git
    git remote add azure https://AdisTeam:ptwrd7n3cjwkchmuwtme4glpn4tyzqw5x6dt6sasuvi57h2kdfja@dev.azure.com/AdisTeam/Bravo%20Seed/_git/Bravo%20Seed
    git branch -D master
    git checkout -b master
    git push -d azure master
    git push -u azure master --force
  displayName: 'synchronization azure repository master branch'
